instaclustr/cassandra-operator

.gitignore, operator/pom.xml, operator/src/main/java/com/instaclustr/cassandra/operator/App.java, operator/src/main/java/com/instaclustr/k8s/K8sModule.java
Shade operator jar for simplified deployment
K8s model now uses Config helper methods for simplified Kubernetes cluster configuration and easy in-cluster detection
Clean up git ignore file
=> Simplify build and k8s client config

buildenv/build, model/src/main/resources/schema/data-center.json, operator/src/main/java/com/instaclustr/cassandra/operator/service/ControllerService.java
Also added local tag to build workflow (doesn't get pushed to repo).
=> Support custom images via the CRD

operator/src/main/resources/com/instaclustr/test-dc.yaml
add `image: instaclustr/k8s-cassandra` into test-dc.yaml for testing
=> added image param for DC test YAML

operator/src/main/java/com/instaclustr/cassandra/operator/DataCenterWatchService.java, operator/src/main/java/com/instaclustr/cassandra/operator/event/DataCenterEvent.java, operator/src/main/java/com/instaclustr/k8s/WatchService.java, operator/src/main/resources/com/instaclustr/datacenter-crd.yaml, operator/src/main/resources/com/instaclustr/test-dc.yaml
... a head bow to American technological and cultural imperialism :)
=> Unified spelling of center to center

model/src/main/resources/schema/data-center.json, operator/src/main/java/com/instaclustr/cassandra/operator/service/ControllerService.java, operator/src/main/resources/com/instaclustr/datacenter-crd.yaml, operator/src/main/resources/com/instaclustr/test-dc.yaml
Newly added params are `imagePullPolicy` `resources` `capacity`
Params to be validated are `replicas` `image` `imagePullPolicy`
sample is `test-dc.yaml`
=> exposed more params for dc creation & enabled params validation

.circleci/config.yml, buildenv/build, buildenv/release
=> tag builds with latest and push

java/operator/src/main/java/com/instaclustr/cassandra/operator/k8s/K8sResourceUtils.java
Same as PR #48. Rebased & cleaned redundent commits.
=> [new] Temporary fix for Unprocessable Entity issue

doc/developers.md, doc/op_guide.md, examples/common/test.yaml
I'm attempting to follow the documentation, and it seems to have drifted away from the code. This attempts to fix what's obvious.
=> Initial documentation testing and cleanup

.circleci/config.yml, buildenv/release-all
Push sidecar images to gcr
Remove broken pivotal tests for the moment
=> Publish sidecar

doc/op_guide.md, examples/common/rbac-bundle.yaml, examples/common/test.yaml
* Added more spec fields, since some of them are required
* Fixed permissions in the RBAC example
* Fixed mvn build instructions
=> Fix examples

doc/resources.md
Fix minor issue on formatting markdown file
=> Minor fixes on formatting

doc/backup_restore.md
=> doco changes

helm/cassandra-operator/templates/clusterrole.yaml
=> permissions to delete pvc

java/operator/src/main/java/com/instaclustr/cassandra/operator/controller/DataCenterReconciliationController.java
=> now we crash JVM on oom

docker/base-openjre/Dockerfile, java/operator/src/main/java/com/instaclustr/cassandra/operator/controller/DataCenterReconciliationController.java
Support setting required kernel capabilites and limits for Cassandra to work good.
=> Set kernel caps properly

helm/cassandra-operator/values.yaml, helm/cassandra/values.yaml
Use a better pull policy
Change helm to use images built off master
=> Fix some Helm default values

doc/backup_restore.md, helm/cassandra/templates/cassandra.yaml, helm/cassandra/values.yaml, java/model/src/main/resources/schema/CassandraBackup.json, java/operator/src/main/java/com/instaclustr/cassandra/operator/controller/DataCenterReconciliationController.java, java/operator/src/main/java/com/instaclustr/cassandra/operator/service/BackupControllerService.java, java/operator/src/main/resources/com/instaclustr/backup-crd.yaml
Fixed cloud backups to support new user-defined config map volumes.
Fixed Helm packages to support backups/user defined config map volumes.
Better error handling for backup API calls.
=> Fix cloud backups

buildenv/release-all, buildenv/release-cassandra
=> fix cassandra docker image release process

examples/common/test.yaml, helm/cassandra/templates/cassandra.yaml, helm/cassandra/values.yaml, java/model/src/main/resources/schema/CassandraDataCenter.json, java/operator/src/main/java/com/instaclustr/cassandra/operator/controller/DataCenterReconciliationController.java, java/operator/src/main/resources/com/instaclustr/datacenter-crd.yaml
Address #116 and allow users to run on clusters that don't support privileged containers.
=> Optional privileged

test/testGCPCassandraValues.yaml
Needed to update for new specs/features
=> Fix GCP test values

.circleci/config.yml, buildenv/build-all, buildenv/release-all, docker/base-openjre/Makefile, docker/cassandra-operator/Makefile, docker/cassandra-sidecar/Makefile, docker/cassandra/Makefile
Docker building was moved to makefiles, change build scripts to leverage makefiles
=> Support Makefiles

docker/circleBuildEnv/Dockerfile, helm/cassandra-operator/templates/clusterrole.yaml, helm/cassandra/templates/cassandra.yaml, java/operator/src/main/java/com/instaclustr/cassandra/operator/controller/DataCenterDeletionController.java, java/operator/src/main/java/com/instaclustr/cassandra/operator/k8s/K8sResourceUtils.java
- #142 couldn't list services
- helm templates would turn a empty string into null :(
=> Fix helm issues

java/operator/src/main/java/com/instaclustr/cassandra/operator/controller/DataCenterDeletionController.java, java/operator/src/main/java/com/instaclustr/cassandra/operator/controller/DataCenterReconciliationController.java, java/operator/src/main/java/com/instaclustr/cassandra/operator/k8s/K8sResourceUtils.java, java/operator/src/main/java/com/instaclustr/cassandra/operator/service/BackupControllerService.java, java/operator/src/main/java/com/instaclustr/cassandra/operator/service/CassandraHealthCheckService.java, java/operator/src/main/java/com/instaclustr/cassandra/operator/service/OperatorService.java
- Fixes issue where some resources wouldn't be cleaned up correctly because the operator didn't paginate through all the results.
=> Adds paging support for various resource lists. 

.gitignore
Files/Directories added:
*  .project
* .classpath
* .settings
* .factorypath
=> Add VSCode-specific files to .gitignore

helm/cassandra/values.yaml
=> Remove -dev image refs

Gopkg.lock, Gopkg.toml, docker/cassandra-operator/Makefile, pkg/sidecar/client.go, pkg/sidecar/client_test.go
=> initial Sidecar client impl

java/operator/src/main/java/com/instaclustr/cassandra/operator/Operator.java, java/operator/src/main/java/com/instaclustr/cassandra/operator/configuration/DeletePVC.java, java/operator/src/main/java/com/instaclustr/cassandra/operator/controller/DataCenterDeletionController.java, java/operator/src/main/java/com/instaclustr/cassandra/operator/controller/DataCenterReconciliationController.java, java/operator/src/main/java/com/instaclustr/cassandra/operator/k8s/K8sResourceUtils.java
- just flag based for the moment.
=> Allow the operator to clean up after itself with pvcs 

helm/cassandra-operator/templates/deployment.yaml, helm/cassandra-operator/values.yaml
=> Support PVC delete in helm charts

pkg/controller/cassandrabackup/reconciler.go, pkg/controller/cassandradatacenter/statefulset.go, pkg/sidecar/client.go, pkg/sidecar/client_test.go, pkg/sidecar/kind_jsonenums.go, pkg/sidecar/operations.go
Sync to lastest java side operations
=> Sync operations

pkg/controller/cassandrabackup/reconciler.go, pkg/sidecar/client.go, pkg/sidecar/operations.go
=> Client updates

docker/cassandra/install-cassandra
resolves https://github.com/instaclustr/cassandra-operator/issues/231
=> added flag to create cassandra home dir so we can bash and cqlsh smoothly

pkg/controller/cassandradatacenter/ports.go, pkg/controller/cassandradatacenter/services.go, pkg/controller/cassandradatacenter/statefulset.go
should resolve https://github.com/instaclustr/cassandra-operator/issues/228
=> consolidated ports

deploy/crds/cassandraoperator_v1alpha1_cassandradatacenter_crd.yaml, pkg/apis/cassandraoperator/v1alpha1/cassandradatacenter_types.go, pkg/apis/cassandraoperator/v1alpha1/zz_generated.openapi.go, pkg/common/cluster/utils.go
=> Make multirack configuration optional

java/sidecar-common/src/main/java/com/instaclustr/sidecar/http/JerseyHttpServerService.java, java/sidecar/src/test/java/com/instaclustr/operations/AbstractSidecarTest.java
Fix race condition where the inheriting tests would bind on the same port.
=> Resolve build errors on mvn test

.circleci/config.yml, buildenv/build-all, buildenv/release-all
This is the set of changes we need to merge when switching to go version. Can be merged to master directly after switching.
=> CircleCI updates for go switch

.circleci/config.yml
=> Fix circleCI checks

pkg/controller/cassandradatacenter/finalizers.go, pkg/controller/cassandradatacenter/metadata.go
try to address https://github.com/instaclustr/cassandra-operator/issues/402
=> use uid to identify PVCs

pkg/controller/cassandradatacenter/statefulset.go
solve https://github.com/instaclustr/cassandra-operator/issues/404
=> using UID to list statefulsets
