instaclustr/cassandra-operator

- backup/pom.xml
The target allows for a uber jar to be created allowing the backup module to be used as a standalone utility. 
Example usage: 
`java -jar backup/target/backup-1.0-SNAPSHOT-final.jar --help`
> Add shading target for backup module

- .circleci/config.yml
> Don't need to run `build` on master as that is done via release-dev

- java/operator/src/main/java/com/instaclustr/cassandra/operator/k8s/K8sResourceUtils.java
- java/operator/src/main/java/com/instaclustr/cassandra/operator/service/ControllerService.java
Now when a pod get deleted (scaling down or DC delete event), it's Persistent Volume and Persistent Volume Claim will also got deleted.
> Remove PVC & PV when scaling down or DC get deleted

- java/operator/src/main/java/com/instaclustr/cassandra/operator/service/CassandraHealthCheckService.java
- java/operator/src/main/java/com/instaclustr/cassandra/operator/service/ControllerService.java
A patch for current critical issues:
- Issue #44: Now skip `Pod`  `cassandraConnection.status()` check on `Pod` which is not in `Running` state. Also as we discussed, the ideal way is to use service to discuss `Running Pod`. However, seems there is no such APIs available for us to use.
- Issue #55: There is a typo that uses `return` instead of `continue`. Therefore, `Controller Service` thread is terminated once a `delete` event happens.
> Fixes for issue #44 #55

- java/backup/pom.xml
Currently the backup module removes sfl4j and logback as it's being shaded. Re-introducing these dependencies back to the backup's pom.xml allows backup to successfully use the logging implementation with a log4j.properties file (using `-Dlog4j.configuration=file:///<path_to>/log4j.properties`). For future reference we may want to include a default log4j file, but for now this solution is sufficient.
> Add logback + slf4j dependencies to java/backup module

- java/backup/src/main/java/com/instaclustr/backup/CommonBackupArguments.java
- java/backup/src/main/java/com/instaclustr/backup/task/BackupTask.java
This is Ben's work from his JMX Branch, hopefully I'm helping get the code commited. Original: https://github.com/benbromhead/cassandra-operator/commits/jmxAuthBackups
> Patch for allowing JMX Auth specification

- docker/cassandra/install-cassandra
- java/model/src/main/resources/schema/CassandraDataCenter.json
- java/operator/src/main/java/com/instaclustr/cassandra/operator/controller/DataCenterReconciliationController.java
This is a branch off `controller-refactor`, hence length of this PR and the duplicate commits & changes.
Things of note:
- New DataCenter CRD fields: `prometheusSupport` (boolean) and `prometheusServiceMonitorLabels` (label key pairs).
- Embedding of the cassandra-exporter Java agent into the Cassandra image.
- Reconcilliation controller optionally enables the exporter agent, exposes the required ports (9500) & creates the `ServiceMonitor` object (part of _prometheus-operator_).
> Prometheus

- helm/cassandra/templates/cassandra.yaml
- helm/cassandra/values.yaml
From feedback in #95 not including the Prometheus support flag would cause an NPE in the operator.
Fix helm package to include Prometheus flags.
> Prometheus support in helm package

- java/operator/src/main/java/com/instaclustr/cassandra/operator/controller/DataCenterReconciliationController.java
Simplified container names inside the pod, it was needlessly verbose
> Container name changes

- java/backup/pom.xml
CVE-2018-11771 More information
moderate severity
Vulnerable versions: < 1.18
Patched version: 1.18
> Fix vulnerability associated with commons compress lib

- buildenv/release-all
I don't think we need to login on release-all as the individual release script calls it
> Fix release-all

- helm/cassandra-operator/templates/deployment.yaml
extensions/v1beta1 Deployments had the selector field as optional, but not apps/v1 Deployments. Upgrading to support new versions
> Fix deployment support for helm chart

- doc/spec_examples.md
- helm/cassandra/templates/cassandra.yaml
- java/operator/src/main/java/com/instaclustr/cassandra/operator/controller/DataCenterReconciliationController.java
- java/operator/src/main/resources/com/instaclustr/datacenter-crd.yaml
Hello,
This PR documents how to use the operator to deploy a datacenter with ssl encryption (see doc/spec_examples.md).
It also fix a few problems in the helm charts :
* add `userSecretVolumeSource`
* template indentation issue 
It disable openapi validation on `userConfigMapVolumeSource` because of a known bug : https://github.com/kubernetes/kubernetes/pull/76124
> support for ssl using user configmap and secret

- buildenv/build-all
- docker/base-openjre/Makefile
- docker/cassandra-operator/Makefile
- docker/cassandra-sidecar/Makefile
- docker/cassandra/Makefile
- docker/cassandra/install-cassandra
Also enables repository-less Docker builds (i.e., on a local machine)
> Update Cassandra image to include LDAP and Kerberos plugins.

- doc/backup_restore.md
- examples/common/backupCrd.yaml
- helm/cassandra/values.yaml
- java/backup/src/main/java/com/instaclustr/backup/common/CloudDownloadUploadFactory.java
- java/backup/src/main/java/com/instaclustr/backup/downloader/AzureDownloader.java
- java/backup/src/main/java/com/instaclustr/backup/task/BackupTask.java
- java/backup/src/main/java/com/instaclustr/backup/task/RestoreTask.java
- java/backup/src/main/java/com/instaclustr/backup/uploader/FilesUploader.java
- java/model/src/main/java/com/instaclustr/backup/BaseArguments.java
- java/model/src/main/resources/schema/CassandraBackup.json
- java/operator/pom.xml
- java/operator/src/main/java/com/instaclustr/cassandra/operator/controller/DataCenterReconciliationController.java
- java/operator/src/main/java/com/instaclustr/cassandra/operator/service/BackupControllerService.java
- java/operator/src/main/resources/com/instaclustr/backup-crd.yaml
- java/sidecar/src/main/java/com/instaclustr/cassandra/sidecar/resource/BackupsResource.java
- java/sidecar/src/main/java/com/instaclustr/cassandra/sidecar/service/backup/BackupService.java
Hello,
Here is the PR that fixes the issues discussed in #152.
What changed :
* an emptydir shared volume mounted at  `/tmp/sidecar-volume-config` by both sidecars and cassandra containers
* restore sidecar writes a fragment config to /tmp/sidecar-volume-config with intial_token and auto_bootstrap disabled.
* cassandra config loader uses /tmp/sidecar-volume-config 
* the operator now set `backup.status.progress` rather than `backup.spec.status`
* basic Azure Storage support (which I used for testing)
* the pods to backup are selected using a `backup.spec.selector` rather than `backup.metadata.labels`
* documentation update
* some fixes
Works on my machine with Azure Storage !
> Backup/restore improvements 

- java/operator/src/main/java/com/instaclustr/cassandra/operator/controller/DataCenterDeletionController.java
- java/operator/src/main/java/com/instaclustr/cassandra/operator/controller/DataCenterReconciliationController.java
- java/operator/src/main/java/com/instaclustr/cassandra/operator/k8s/OperatorLabels.java
- java/operator/src/main/java/com/instaclustr/cassandra/operator/service/CassandraHealthCheckService.java
- java/operator/src/main/java/com/instaclustr/cassandra/operator/service/OperatorService.java
- java/operator/src/main/java/com/instaclustr/cassandra/operator/watch/ConfigMapWatchModule.java
- java/operator/src/main/java/com/instaclustr/cassandra/operator/watch/StatefulSetWatchModule.java
- java/operator/src/main/java/com/instaclustr/k8s/K8sLabels.java
- java/operator/src/main/java/com/instaclustr/k8s/LabelSelectors.java
- Fixes incorrect label selector defined for WatchServices which prevented them from observing modification events.
- Simplifies triggering logic for reconciliation on StatefulSet changes.
> Fixes incorrect label selector on StatefulSet and ConfigMaps

- Makefile.inc
- docker/base-openjre/Makefile
- docker/cassandra-operator/Makefile
- docker/cassandra-sidecar/Makefile
- docker/cassandra/Makefile
My Fedora uses [Buildah](https://buildah.io/) to build images with parameters. Because of that, I decided to add some conditionals to look for buildah in the path and run it instead of docker if present.
Fixes #147
> Add conditional in Makefiles in order to use other image builders

- cmd/manager/main.go
The slash causes startup errors. This looks like a typo to me.
> Remove slash from leader ConfigMap name

- docker/cassandra-sidecar/Dockerfile
Fixes https://github.com/instaclustr/cassandra-operator/issues/212.
Using a [shell-form entrypoint](https://docs.docker.com/engine/reference/builder/#shell-form-entrypoint-example) causes PID 1 to be a shell which prevents signals from reaching the application. The result is slow termination of Cassandra pods.
> Make sidecar respond to signals

- docker/cassandra-sidecar/Dockerfile
- docker/cassandra/Dockerfile
- docker/cassandra/default-config/cassandra-env.sh.d/002-cassandra-limits.sh
- docker/cassandra/install-cassandra
This PR makes C* and the sidecar run as a non-root user. Rationale:
- Running containers as root is less secure than non-root.
- Some clusters employ PSPs which prevent running containers as root. This change makes it possible to use the operator even on clusters with strict PSPs.
- As far as I can tell, root isn't really necessary for C* nor for the sidecar.
> Run Cassandra and sidecar as non-root

- buildenv/build
- buildenv/build-all
- buildenv/build-cassandra
- buildenv/release
- buildenv/release-all
- buildenv/release-cassandra
- buildenv/repo
- doc/developers.md
- docker/base-openjre/Makefile
- docker/cassandra-operator/Makefile
- docker/cassandra-sidecar/Makefile
- docker/cassandra/Makefile
The current state generates tags such as `registry/repocassandra` instead of `registry/repo/cassandra`.
I'm assuming there should be slashes here from looking at the other Makefiles, for example [this one](https://github.com/instaclustr/cassandra-operator/blob/cfb76a760d0b6f1c5dcc272c758adb18b5109254/docker/cassandra-sidecar/Makefile#L19-L20).
> Fix Docker image name handling

- java/backup-restore/src/main/java/com/instaclustr/cassandra/backup/cli/BackupApplication.java
- java/backup-restore/src/main/java/com/instaclustr/cassandra/backup/cli/BackupRestoreCLI.java
- java/backup-restore/src/main/java/com/instaclustr/cassandra/backup/cli/CommitLogBackupApplication.java
- java/backup-restore/src/main/java/com/instaclustr/cassandra/backup/cli/CommitLogRestoreApplication.java
- java/backup-restore/src/main/java/com/instaclustr/cassandra/backup/cli/RestoreApplication.java
- java/common/src/main/java/com/instaclustr/picocli/CLIApplication.java
- java/common/src/main/java/com/instaclustr/picocli/JarManifestVersionProvider.java
- java/common/src/main/java/com/instaclustr/version/Version.java
- java/common/src/main/java/com/instaclustr/version/VersionModule.java
- java/common/src/test/java/com/instaclustr/version/VersionTest.java
- java/sidecar/src/main/java/com/instaclustr/cassandra/sidecar/Sidecar.java
- java/sidecar/src/main/java/com/instaclustr/cassandra/sidecar/picocli/SidecarJarManifestVersionProvider.java
Version object is populated from JarManifestVersionProvider and sidecar endpoint returns build time, commit log and so on. This information is also logged on -v or --version switch on CLI and it is logged everytime such command is invoked at the very beginning.
> Version object populated from JarManifestVersionProvider and logged in CLI commands too

- docker/cassandra-operator/Dockerfile
This improves the cacheability of the Docker image since Go modules will now be re-downloaded only when there is a change to `go.mod` or `go.sum`.
> Improve Docker caching

- pkg/controller/cassandradatacenter/cassandradatacenter_controller.go
- pkg/controller/cassandradatacenter/configmap.go
- pkg/controller/cassandradatacenter/services.go
- pkg/controller/cassandradatacenter/statefulset.go
The current reconcile loop is not going to work if the decommission or creating of the new nodes takes a long time. The events that the reconcile responds to will come in fast initially, and if the cluster is undergoing an operation, the operator will do nothing with those events.
This change fixes this issue by requesting a repeat of the handler call after 1 minute after detecting that the cluster is in a "non-ready state"; this way the handler will always be called until all the events are worked out on and the cluster is reconciled to the new requested state. This works for building, scaling up and scaling down scenarios.
> Improve reconcile loop

- deploy/crds/cassandraoperator_v1alpha1_cassandradatacenter_crd.yaml
- docker/cassandra/Dockerfile
- docker/cassandra/entry-point
- docker/cassandra/install-cassandra
- docker/cassandra/wrapper
- examples/go/example-datacenter.yaml
- go.mod
- pkg/apis/cassandraoperator/v1alpha1/cassandradatacenter_types.go
- pkg/apis/cassandraoperator/v1alpha1/zz_generated.openapi.go
- pkg/controller/cassandradatacenter/configmap.go
- pkg/controller/cassandradatacenter/helpers.go
- pkg/controller/cassandradatacenter/statefulset.go
This PR makes kernel performance tweaks optional. These are controlled using the `optimizeKernelParams` field in the CRD.
By default, the C* pods created by the operator will run in the following mode:
- `sysctl` isn't called (the init container isn't included in the pod).
- `ulimit` isn't called.
- `disk_access_mode` is set to the default (`auto`).
- C* is unable to use the `mlock`/`mlockall` syscalls. A warning is written to the log.
When the user sets `optimizeKernelParams` to `true`, the C* pods will run in the following mode:
- `sysctl -w vm.max_map_count=1048575` is executed in an init container. This changes the parameter **globally** on the host. Any related documentation should reflect that.
- `ulimit -l unlimited` is executed on C* startup. This change affects only the C* …
> Make kernel tweaks optional

- deploy/cassandra/psp.yaml
- deploy/cassandra/psp_performance.yaml
This PR adds two PSPs as well as their required RBAC "wiring" - ServiceAccount, Role and RoleBinding.
We provide two policies to match the two modes (https://github.com/instaclustr/cassandra-operator/pull/269) supported by the operator: "normal" (default) and "performance" (`optimizeKernelParams: true`).
The user can apply *both* manifests to a cluster with no negative effects since only when specifying `serviceAccountName` in the CR is a policy actually applied.
On clusters with a loose security policy (most clusters are) the operator will likely work even without explicitly using either of the PSPs, however we may still want to attach `deploy/cassandra/psp.yaml` to the C* pods by default by specifying `serviceAccountName: cassandra` in the CR.
> Add PSPs for Cassandra pods

- .circleci/config.yml
- docker/cassandra-operator/Dockerfile
- go.mod
- go.sum
- test/e2e/cassandra_test.go
- test/e2e/main_test.go
- test/e2e/utils.go
This adds the `goimports` check to CI validating that the code is properly formatted and imports are aligned (cleaned, grouped and sorted alphabetically)
> CI gofmt check

- deploy/crds/cassandraoperator_v1alpha1_cassandradatacenter_crd.yaml
- pkg/apis/cassandraoperator/v1alpha1/cassandradatacenter_types.go
- pkg/apis/cassandraoperator/v1alpha1/zz_generated.openapi.go
- pkg/controller/cassandradatacenter/statefulset.go
The `fsGroup` field in a pod's SecurityContext allows controlling the GID of volume mounts. This is important when non-root processes need write permissions to k8s volumes.
> Allow specifying fsGroup for C* pods

- deploy/configmap.yaml
The operator depends on this ConfigMap so we need to deploy it along with the operator.
> Add default operator config ConfigMap

- .circleci/config.yml
- .circleci/validate_repo.sh
- go.mod
- go.sum
Additional "repo" checks in CI will validate that OpenAPI and k8s
objects are in sync with the code changes; as well as that `make bundle`
was rerun and is also in sync with the current code state.
> Added more checks in CI

- doc/rbac.md
Very minor change to docs to add YAML highlighting in example permissions
> Use yaml highlighting

- deploy/bundle.yaml
- deploy/cassandra/psp.yaml
- deploy/cassandra/psp_performance.yaml
The field was accidentally copy-pasted when creating the manifests.
> Remove creationTimestamp field from PSP manifests

- deploy/bundle.yaml
- deploy/configmap.yaml
- deploy/crds.yaml
- deploy/crds/cassandraoperator_v1alpha1_cassandradatacenter_crd.yaml
- doc/op_guide.md
- go.sum
- pkg/apis/cassandraoperator/v1alpha1/cassandradatacenter_types.go
- pkg/apis/cassandraoperator/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/cassandraoperator/v1alpha1/zz_generated.openapi.go
- pkg/controller/cassandradatacenter/cassandradatacenter_controller.go
- pkg/controller/cassandradatacenter/statefulset.go
solves https://github.com/instaclustr/cassandra-operator/issues/165
This effectively enables people to run whole Cassandra cluster in memory or with normal disk but it is backed by `EmptyDir` from Kubernetes so no claims & co. are necessary ...
It is compatible with data volume claim we have currently, it will just fallback to EmptyDir if it is not specified.
> implemented EmptyDir volume for pod

- pkg/controller/cassandradatacenter/metadata.go
The guard to avoid a `nil` panic checks `operatorLabels` instead of `operatorAnnotations`.
> Use correct guard for missing annotations to avoid panic

- helm/cassandra-operator/Chart.yaml
- helm/cassandra-operator/templates/deployment.yaml
- helm/cassandra-operator/values.yaml
This change will allow setting the 'WATCH_NAMESPACE' behaviour from values.yaml so that it can be used with overrides, without having to edit the helm chart.
Thanks,
Frank
> added watch_namespace to values.yaml

- helm/cassandra/templates/cassandra.yaml
The infix position should not be used and results in an error starting with go 1.14, explanation [here](https://github.com/helm/helm/issues/7711#issuecomment-593113347). I've simplified the clause as used in e.g. [`passwordAuth`](https://github.com/instaclustr/cassandra-operator/blob/master/helm/cassandra/templates/cassandra.yaml#L84)
I've stumbled upon this one as I'm using the https://github.com/fluxcd/helm-operator which doesn't support helm registries yet, so I had to use the git repo as a source directly, in which case go 1.14 is used to build the helm file.
> simplify if clause of optimizeKernelParams in cassandra helm template for go 1.14 compability
